pipeline:
  build:
    image: ubuntu:xenial
    commands:
      - git clone https://github.com/eisoku9618/kuroiwa_demos.git
      - cd tex; make

services:
  postgres:
    image: postgres:9.4.5
    environment:
      - POSTGRES_USER=myapp
