pipeline:
  build:
    image: ubuntu:xenial
    commands:
      - apt list --installed
      - apt update
      - apt install git -y
      - git clone https://github.com/eisoku9618/kuroiwa_demos.git
      - cd kuroiwa_demos/tex; ls; make

services:
  postgres:
    image: postgres:9.4.5
    environment:
      - POSTGRES_USER=myapp
